### ISSUE TITLE
change css style

### ISSUE THREAD

**Issue by maywanting** [MikeCoder/hexo-tag-cloud#1]
I have used your widget, and sure it's nice. But the default font style like font-color, font-family is not suitable to my blog's theme. Can you provide an improvement so that we can write the css freely.

**Comment by D0n9X1n** [comment]
you can see the readme file the [customize part](https://github.com/MikeCoder/hexo-tag-cloud#customize).

**Comment by D0n9X1n** [comment]
See 2.0.\* version.
