### ISSUE TITLE
tag cloud can't show up

### ISSUE THREAD

**Issue by BlinkOneMoreTime** [MikeCoder/hexo-tag-cloud#13]
## Expected Behavior 
The tags should show up on the side bar

## Actual Behavior
nothing happened

## Steps to Reproduce the Problem

  1.  the .js files(tagcanvas, tagcloud) have been existed and I also insert the code into the side bar 
```
  <div class="site-state-item">
              {% if site.tags.length > 1 %}
                <script type="text/javascript" charset="utf-8" src="/js/tagcloud.js"></script>
                <script type="text/javascript" charset="utf-8" src="/js/tagcanvas.js"></script>
                <div class="widget-wrap">
                    <h3 class="widget-title">Tag Cloud</h3>
                    <div id="myCanvasContainer" class="widget tagcloud">
                        <canvas width="250" height="250" id="resCanvas" style="width=100%">
                            {{ list_tags() }}
                        </canvas>
                    </div>
              </div>
              {% endif %}
           </div> 
```

## Specifications
(The version of the project, operating system, hardware etc.)
Thank you very much.

**Comment by D0n9X1n** [comment]
I think your blog is not based on the `hexo` blog system. This plugin should be used as a plugin by hexo.

If you want to add a 3D tag cloud into your blog, you can read this [URL](http://www.goat1000.com/tagcanvas.php)
