### ISSUE TITLE
how to edit this widget file of which the filetype is pug 

### ISSUE THREAD

**Issue by SnailDove** [MikeCoder/hexo-tag-cloud#14]
How to add the “hexo-tag-cloud” widget to the theme [maupassant-hexo](https://github.com/tufu9441/maupassant-hexo) ,  the filepath of the widget of this theme is "maupassant-hexo/layout/_widget/" and the filetype of the widgets is "*.pug" , I copied "tagcloud.jade" to this filepath, but it doesn't work and satisfy my needs.

**Comment by min-zou** [comment]
https://github.com/MikeCoder/hexo-theme-gandalfr.git 下找到archive.jade文件，将block container下的内容，复制到自己博客文件下的archive.pug中，同时将hexo-theme-gandalfr.git下的mixins/post.jade文件拷贝到layout目录下，在之前的archive.pug文件中修改相应的路径即可。
