### ISSUE TITLE
修改 outlineMethod = size

### ISSUE THREAD

**Issue by liuzhihang** [MikeCoder/hexo-tag-cloud#17]
当前情况为默认 outlineMethod = block 不知道如何配置 还是当前不支持配置

**Comment by D0n9X1n** [comment]
目前不支持，你可以先自行修改下:[index.js#L66](https://github.com/MikeCoder/hexo-tag-cloud/blob/510b4c2b2459aefec725d00cf0ce03413412bb45/index.js#L66)，把 block 改为 size。
