### ISSUE TITLE
再次打扰您，请问如何设置让球体的大小变大？

### ISSUE THREAD

**Issue by Palpitation-github** [MikeCoder/hexo-tag-cloud#20]
大佬您好。我在TagCanvas的官网看到了好多可以在_config.yml中修改球体大小的选项，但是因为理解能力不够，并未成功修改，可以帮帮孩子嘛，蟹蟹

**Comment by D0n9X1n** [comment]
https://github.com/MikeCoder/hexo-tag-cloud/blob/master/README.ZH.md#%E8%87%AA%E5%AE%9A%E4%B9%89

**Comment by Palpitation-github** [comment]
但是这里面没有可以设置整个球形大小的呀，[tag页](https://voidmaker69.github.io/tags/)并没有成功

**Comment by D0n9X1n** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/3142935/48718485-75a6ac00-ec56-11e8-8710-37a0ba6482a4.png">

这个值修改一下。

**Comment by Palpitation-github** [comment]
原来如此，超级感谢，这么晚了还打打扰您蟹蟹！您也早睡呦，明天我也去试试，安啦

**Comment by Palpitation-github** [comment]
搞定啦，再次感谢！
