### ISSUE TITLE
不知道还在不在，但是仍想打扰

### ISSUE THREAD

**Issue by XTZORZ** [MikeCoder/hexo-tag-cloud#21]
这个标签云能在哪里修改它的速度啊。。
以上

**Comment by D0n9X1n** [comment]
目前的话，不支持配置。之后会支持更多的配置。

你可以自己先改下代码：https://github.com/MikeCoder/hexo-tag-cloud/blob/0b4458fe7992c92e91bcf394dbe83bf8f690adf6/lib/tagcanvas.js#L2157

把这个数字提高，取值范围是 [0.01 ~ 5]

**Comment by D0n9X1n** [comment]
Fixed, see https://github.com/MikeCoder/hexo-tag-cloud#customize
