### ISSUE TITLE
您好，大佬，目前标签页无法显示

### ISSUE THREAD

**Issue by Palpitation-github** [MikeCoder/hexo-tag-cloud#22]
打扰您啦，这是我的标签页地址
https://dlovexj.cn/tags/
我是按照您的说明之前成功的，但是现在我使用的主题更新了，不过在关键位置跟之前几乎是一样哒，我还是按照之前的方法，先安装插件，然后在page-header.ejs 处添加代码，可是并没有出现，包括hexo s 也没有出现，可以帮帮我嘛，蟹蟹，♥

**Comment by D0n9X1n** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/3142935/55721014-d7648880-5a34-11e9-8f16-ca8a7dff4bc4.png">

你的代码添加的不对，tagcanvas.js 和 tagcloud.js 的链接都需要改一下。

tagcanvas.js 的链接是 https://dlovexj.cn/js/tagcanvas.js, 你也可以写成 `/js/tagcanvas.js`

tagcloud.js 的链接是 https://dlovexj.cn/js/tagcloud.js, 你也可以写成 `/js/tagcloud.js`

**Comment by D0n9X1n** [comment]
https://github.com/MikeCoder/hexo-tag-cloud#for-ejs-users

<img width="679" alt="image" src="https://user-images.githubusercontent.com/3142935/55721182-404c0080-5a35-11e9-8ed5-f88d5d3f19ee.png">

**Comment by Palpitation-github** [comment]
修改啦但是还是不显示，是因为主题的问题嘛，https://github.com/Sariay/hexo-theme-Annie

**Comment by D0n9X1n** [comment]
主题问题，主题中有代码里有覆盖了 window.onload 函数，导致 tag cloud 函数钩子不执行。


#### 验证手段
在页面加载好之后，你可以把以下代码插入放到 console 里面执行。可以看到标签云。你可以去主题里面提个 issue，不要暴力直接 `window.onload = func() {...}`。

```
    try {
        TagCanvas.textFont = 'Trebuchet MS, Helvetica';
        TagCanvas.textColour = '#333';
        TagCanvas.textHeight = 18;
        TagCanvas.outlineColour = '#E2E1C1';
        TagCanvas.maxSpeed = 0.03;
        TagCanvas.outlineMethod = 'block';
        TagCanvas.minBrightness = 0.2;
        TagCanvas.depth = 0.92;
        TagCanvas.pulsateTo = 0.6;
        TagCanvas.initial = [0.1,-0.1];
        TagCanvas.decel = 0.98;
        TagCanvas.reverse = true;
        TagCanvas.hideTags = false;
        TagCanvas.shadow = '#ccf';
        TagCanvas.shadowBlur = 3;
        TagCanvas.weight = false;
        TagCanvas.imageScale = null;
        TagCanvas.fadeIn = 1000;
        TagCanvas.clickToFront = 600;
        TagCanvas.Start('resCanvas');
        TagCanvas.tc['resCanvas'].Wheel(false)
    } catch(e) {
        console.log(e);
        document.getElementById('myCanvasContainer').style.display = 'none';
    }
```

**Comment by Palpitation-github** [comment]
嗯嗯知道哒，emmm那我该怎么修改才可以避免这个问题呢，emmm小白不太懂，只能等作者改主题嘛

**Comment by D0n9X1n** [comment]
目前，是的。

或者你问下那个主题作者，怎么能把上面那段代码加进主题的 window.onload 函数里。这点他应该比我清楚。

**Comment by Palpitation-github** [comment]
非常感谢您百忙之中的帮助，蟹蟹😘

**Comment by leafjame** [comment]
> 嗯嗯知道哒，emmm那我该怎么修改才可以避免这个问题呢，emmm小白不太懂，只能等作者改主题嘛

请问下这个问题现在解决了嘛？😝😝
