### ISSUE TITLE
我添加了hexo-tag-cloud，但是我的tags页完全没有改变。

### ISSUE THREAD

**Issue by jerrywcy** [MikeCoder/hexo-tag-cloud#24]
我在我的theme文件夹下找不到tagcloud.ejs文件
我的theme是alpha_dust
hexo版本是3.9.0
但landscape的theme文件夹下就有tagcloud.ejs文件
next的theme文件夹下也能找到sidebar.swig文件
只有alpha_dust的theme文件夹下没有
![image](https://user-images.githubusercontent.com/34678939/61511442-58b2ba80-aa29-11e9-8b89-07c9f5d1e1c1.png)
![image](https://user-images.githubusercontent.com/34678939/61511492-87309580-aa29-11e9-9955-4e1f13923abf.png)
![image](https://user-images.githubusercontent.com/34678939/61511536-a62f2780-aa29-11e9-8c44-0260b02aaf3c.png)
这是我的标签页链接：https://jerrywcy.github.io/tags/
![image](https://user-images.githubusercontent.com/34678939/61512041-476aad80-aa2b-11e9-810a-58f8cc49ceb6.png)
似乎完全没有加载出来的样子
能帮忙看看嘛？
麻烦大佬了！

**Comment by jerrywcy** [comment]
我现在使用的主题就是alpha_dust
![image](https://user-images.githubusercontent.com/34678939/61512258-e8f1ff00-aa2b-11e9-835c-6e3457685b24.png)
![image](https://user-images.githubusercontent.com/34678939/61512262-eb545900-aa2b-11e9-95cd-18de5dd7bcec.png)
![image](https://user-images.githubusercontent.com/34678939/61512267-edb6b300-aa2b-11e9-9514-b0b7faa32966.png)
package.json里的依赖是它自己添加的，我没改过

**Comment by jerrywcy** [comment]
前两张图片是根目录下的配置文件，第三个是package.json

**Comment by D0n9X1n** [comment]
看了看代码是在 `https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/page.ejs` 这里，你就按照下面的方法，把 Tag Cloud 的代码加进去就好，title 和样式自己调整下就好了。
```ejs
<div class="row">
    <div class="col-sm-12">

        <!--Title and Logo-->
        <% if (page.type === 'tags' || page.type === 'tag') { %>
            <%- partial('_partial/header.ejs', {logoIcon: page.logoIcon || 'fa-tags', headerTitle: page.title}) %>

<!-- Tag Cloud Code -->
            <% if (site.tags.length) { %>
            <script type="text/javascript" charset="utf-8" src="<%- url_for('/js/tagcloud.js') %>"></script>
            <script type="text/javascript" charset="utf-8" src="<%- url_for('/js/tagcanvas.js') %>"></script>
            <div class="widget-wrap">
                <h3 class="widget-title"><%= __('tagcloud') %></h3>
                <div id="myCanvasContainer" class="widget tagcloud">
                <canvas width="250" height="250" id="resCanvas" style="width=100%">
                    <%- tagcloud() %>
                </canvas>
                </div>
            </div>
            <% } %>
<!-- Tag Cloud Code -->

            <section class="main archive-container">
                <% site.tags.forEach(function(tag) { %>
                        <%- partial('_partial/tag-cat-item', {item: {path: tag.path, title: '#' + tag.name}}) %>
                <% }); %>
            </section>
        <% } else if (page.type === 'categories' || page.type === 'category') { %>
            <%- partial('_partial/header.ejs', {logoIcon: page.logoIcon || 'fa-folder-open', headerTitle: page.title}) %>
            <section class="main archive-container">
                <% site.categories.forEach(function(cat) { %>
                        <%- partial('_partial/tag-cat-item', {item: {path: cat.path, title: cat.name}}) %>
                <% }); %>
            </section>
        <% } else { %>
            <%- partial('_partial/header.ejs', {logoIcon: page.logoIcon, headerTitle: ''}) %>
            <section class="main">
                <%- partial('_partial/article-long', {item: page}) %>
            </section>
        <% } %>
    </div>
</div>
```

**Comment by jerrywcy** [comment]
有标签云了，谢谢大佬！
