### ISSUE TITLE
你好，可以切换为普通标签云吗

### ISSUE THREAD

**Issue by fyzhu** [MikeCoder/hexo-tag-cloud#25]
## Expected Behavior 
你好，可以切换为普通标签云吗，不使用canvas

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
没有很明白你的意思，

普通标签云的话，hexo 提供了 tag 相关的函数，直接看具体主题实现就行，这个需要咨询主题作者。
