### ISSUE TITLE
请问是否支持设置：在鼠标覆盖到文字后不要暂停球体的转动

### ISSUE THREAD

**Issue by morainzh** [MikeCoder/hexo-tag-cloud#26]
RT
这样会显得标签云一卡一卡的
https://morainzh.org

**Comment by MikeCoder** [comment]
周末修复。感谢。

**Comment by hoochanlon** [comment]
个人想法：如果含有鼠标悬停所选标签，则排除其转动范围，其他的标签继续保持球体的转动

**Comment by jerrywcy** [comment]
我去看了，tagcanvas网站上提供的样例就是不会停的啊

**Comment by D0n9X1n** [comment]
1. Upgrade to v2.1.2
2. See https://github.com/MikeCoder/hexo-tag-cloud#customize
3. Add `pauseOnSelected: false`
