### ISSUE TITLE
请问部署完毕后在哪查看啊

### ISSUE THREAD

**Issue by littlegreedy** [MikeCoder/hexo-tag-cloud#27]

**Comment by D0n9X1n** [comment]
部署之后，需要主动修改模版文件。

https://github.com/MikeCoder/hexo-tag-cloud#install

最终显示效果以修改后的模版为准。

**Comment by littlegreedy** [comment]
当然，我的确修改了模板文件，之后呢？

**Comment by D0n9X1n** [comment]
emmm, 那就在你改模板的那个页面啊。。
你改的哪边就显示在哪边啊。

**Comment by hoochanlon** [comment]
贴上配置、图片，这样方便我们解决问题

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
