### ISSUE TITLE
你好作者，使用的next主题，但是按照你说的方法假如之后无效

### ISSUE THREAD

**Issue by RogueAndy** [MikeCoder/hexo-tag-cloud#28]
你好作者，使用的next主题，但是按照你说的方法假如之后无效，以下是next主题的链接:
https://github.com/theme-next/hexo-theme-next

按照你的方法，在路径/next/layout/_macro/sidebar.swig文件，打开之后，我在最后添加的代码。
添加完毕之后，在博客根目录下，_config.yml文件，添加tag_cloud配置，但是还是无效，麻烦你帮我看一下

**Comment by D0n9X1n** [comment]
具体是什么原因? 是 js 没能加载还是在指定页面上没有出现对应的 div ?
