### ISSUE TITLE
tagcloud无法在icarus主题下的右侧widget处显示。

### ISSUE THREAD

**Issue by wangyx1107** [MikeCoder/hexo-tag-cloud#31]
Tag cloud无法在icarus主题下的右侧widget处显示。
在左侧和下方都显示正常，但在右侧无法显示（有tagcloud的标题,看不到球体）
<br/>
用朋友的icarus主题blog的tag cloud放在右侧显示，也出现同样的问题，应该不是我的个例问题。
<br/>

左侧（正常）
![](https://s2.ax1x.com/2020/02/17/3CoWTO.png)
右侧（异常）
![](https://s2.ax1x.com/2020/02/17/3CTwut.png)

[[click]我的icarus主题blog链接（tagcloud暂时放右侧）](https://arthas.org)
查看tagcloud在左侧的显示效果可将网页以一半屏幕大小显示

另：作者您提供的ejs代码无法在icarus主题下正常显示widget的白色背景
可以使用以下代码替换（~/themes/icarus/layout/widget/tagcloud.ejs）
```
<% if (site.tags.length) { %>
<div class="card widget">
    <div class="card-content">
        <h3 class="menu-label">
            <%= __('widget.tag_cloud') %>
        </h3>
        <script type="text/javascript" charset="utf-8" src="<%- url_for('/js/tagcloud.js') %>"></script>
        <script type="text/javascript" charset="utf-8" src="<%- url_for('/js/tagcanvas.js') %>"></script>
        <canvas width="250" height="250" id="resCanvas" style="width:100%">
            <%- tagcloud() %>
        </canvas>
    </div>
</div>
<% } %>
```

**Comment by D0n9X1n** [comment]
抱歉, 未能找到原因.. 目前只能先放在左边栏吧.

**Comment by wangyx1107** [comment]
没事，大概和主题的具体机制有关。
诡异的问题。。。
