### ISSUE TITLE
如果是NexT主题该怎么办？

### ISSUE THREAD

**Issue by cybeird** [MikeCoder/hexo-tag-cloud#5]

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by D0n9X1n** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by MikeCoder** [comment]
可以参考 [http://yoshinorin.net/all-tags/](http://yoshinorin.net/all-tags/), 把标签云放在 tags 页面。

**Comment by D0n9X1n** [comment]
See [issue 6](https://github.com/MikeCoder/hexo-tag-cloud/issues/6)
