### ISSUE TITLE
能否自定义标签大小?

### ISSUE THREAD

**Issue by gcgeng** [MikeCoder/hexo-tag-cloud#9]
标签云中能够同时显示的标签好像有点少QAQ
同时感谢作者提供的插件

**Comment by D0n9X1n** [comment]
[https://github.com/MikeCoder/hexo-tag-cloud#customize](https://github.com/MikeCoder/hexo-tag-cloud#customize)
参照这个自定义配置，然后在 textHeight 这个字段加大。就可以增大标签的大小。
记得修改之后 `hexo clean && hexo g && hexo s` 查看效果。
